version: "3"
services:
  redis:
    container_name: redis
    image: redis
    ports:
      - "6379:6379"

  web:
    build: .
    container_name: web
    ports:
      - "8080:8080"
    volumes:
      - /home/ubuntu:/config
    depends_on:
      - redis
